services:
  user_interface:
    build: frontend
    ports:
      - "8000:8501"
    env_file:
      - "backend/.env"
    develop:
      watch:
        - action: sync
          path: frontend
          target: /develop
  server:
    build: backend
    ports:
      - "8080:5000"
    develop:
      watch:
        - action: sync
          path: backend
          target: /develop
  mongo_db:
    image: mongo
    restart: always
    ports:
      - "8081:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
